### ISSUE TITLE
Product fields are cropped

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix-bookstore#50]
Even on the maximum screen width.

![image](https://user-images.githubusercontent.com/5513878/203783350-bfe594a9-1eb2-468d-af2e-b5fda71ecca3.png)

**Comment by mariodavid** [comment]
done as part of bigger UI improvements in https://github.com/jmix-framework/jmix-bookstore/commit/e89c768daa61c44b1b55bbbc7219b5b9d65e87cd.
