### ISSUE TITLE
Do not recreate data on each start

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix-bookstore#52]
It slows down startup.
Check if some data already exists in the database or introduce a property to bypass this process.

**Comment by mariodavid** [comment]
Yes, we can do that.

The only data where it actually makes sense to have it dynamically generated are Orders (and associated data like Order Lines).

I mainly created the java code not to have to come up with test data on my own. But for the most part we can surely take a dump of the data and put it into SQL scripts as migration scripts. I already did that for part  of the data like Regions, Territories and so on.

**Comment by mariodavid** [comment]
done in #55
