### ISSUE TITLE
Fix "Approve" button for procurement approval stage

### ISSUE THREAD

**Issue by AmirShelli** [jmix-framework/jmix-bookstore#9]
* fill up inventory from Order Fulfillment Manager's account
* Wait for supplier order
* Proceed the task from Procurement Specialist's account
* Log in to Procurement Manager account, open tasks
* Approve order

A.R:
Nothing happens when clicking on the button
<img width="1280" alt="Screenshot 2024-06-21 at 15 16 24" src="https://github.com/jmix-framework/jmix-bookstore-2/assets/42302276/f99045da-1a7c-4653-92b7-f454ee2a4080">

**Comment by knstvk** [comment]
Fixed in 5b10aae
